plugins {
	id 'java'
}

group = 'com.jamescornwell'
version = '0.1.0'

repositories {
	mavenLocal()
	maven {
		url = 'https://repo.runelite.net'
		content {
			includeGroupByRegex('net\\.runelite.*')
		}
	}
	mavenCentral()
}

def runeLiteVersion = 'latest.release'
def pluginMainClass = 'com.jamescornwell.seachartnavigator.SeaChartNavigatorPluginTest'

dependencies {
	compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion

	testImplementation 'junit:junit:4.13.2'
	testImplementation group: 'net.runelite', name: 'client', version: runeLiteVersion
	testImplementation group: 'net.runelite', name: 'jshell', version: runeLiteVersion
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release.set(11)
}

tasks.withType(Test).configureEach {
	useJUnit()
}

tasks.named('jar') {
	archiveBaseName.set('sea-chart-navigator')
}

tasks.register('run', JavaExec) {
	group = 'application'
	description = 'Launches RuneLite with Sea Chart Navigator loaded in developer mode.'
	classpath = sourceSets.test.runtimeClasspath
	mainClass = pluginMainClass
	jvmArgs '-ea'
	args '--developer-mode', '--debug'
}
